### ISSUE TITLE
Issue while trying to run create_device

### ISSUE THREAD

**Issue by bengris32** [efidroid/projectmanagement#138]
Here is what I did:
create_device ./imgs/boot.img 
Device name (vendor/codename): motorola/athene
Device Description (i.e. Moto E): Moto G4 Plus
LCD Density: 401
Available targets:
                 msm8996                 msm7627a                  apq8084                  msm8226
                 msm8610                  msm8660                  msm8960                  msm8974
                 msm8994                  msm8909                  msm8916                  msm8952
LK Target: msm8952
Error: [Errno 2] No such file or directory: 'build/templates/lk_inc.template.mk'
Traceback (most recent call last):
  File "/home/ben/efidroid/build/tools/create_device", line 232, in <module>
    runmain(main)
  File "/home/ben/efidroid/build/tools/../core/utils.py", line 91, in runmain
    sys.exit(main(sys.argv[1:]))
  File "/home/ben/efidroid/build/tools/create_device", line 228, in main
    copyfile('build/templates/lk_inc.template.mk', devicedir+'/lk_inc.mk')
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'build/templates/lk_inc.template.mk'

**Comment by bengris32** [comment]
nvm the building guide is out of date, sorry!
