### ISSUE TITLE
fastboot wrapper improvements

### ISSUE THREAD

**Issue by z3ntu** [efidroid/projectmanagement#64]
`fastbootwrapper oem screenshot 0` gives back an error because the path wasn't given
```
$ fastbootwrapper oem screenshot 0
Error: write() argument must be str, not bytes
Traceback (most recent call last):
  File "/usr/local/bin/fastbootwrapper", line 150, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/fastbootwrapper", line 128, in main
    return read_b64data(argv, 3)
  File "/usr/local/bin/fastbootwrapper", line 110, in read_b64data
    sys.stdout.write(data_decoded)
TypeError: write() argument must be str, not bytes
```
There should be a help message how to use it and/or instructions in the wiki.

**Comment by M1cha** [comment]
I've improved the code and updated the wiki documentation.
